### PR TITLE
[Task#67873] Create migration

### PR DESCRIPTION
**Pull request by namnt0413**
## Related Tickets:

-   [#67873](https://edu-redmine.sun-asterisk.vn/issues/67873)

## WHAT this PR does?
- Khởi tạo các migration ứng với database đã tạo

## Notes Impacted Areas:

-   N/A.

## Attachments:

Screenshot 2023-09-12 152842

### CODE REVIEW

**Comment by tuanngoc1601** [comment]
ok

**Comment by vutuankiet4599** [comment]
commented

**Comment by namnt0413** [comment]
ready

**Comment by vutuankiet4599** [comment]
ok

**Pull request merged**
