### PR TITLE
init

### PR DESCRIPTION
**Pull request by vutuankiet4599**
## Related Tickets:

-   [#67865](https://edu-redmine.sun-asterisk.vn/issues/67865)

## WHAT this PR does?

- Khởi tạo project, thêm ci và pull request template

## Notes Impacted Areas:

-   N/A.

## Attachments:

image

### CODE REVIEW

**Comment by namnt0413** [comment]
oke

**Comment by vutuankiet4599** [comment]
ready

**Review by ghost — COMMENTED** [review]
ready rồi chuyển ticket sang reviewing.

**Comment by vutuankiet4599** [comment]
ready

**Review by ghost — APPROVED** [review]

**Pull request merged**
